# Nome do banco, usuario e senha
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: root

# Driver jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate e JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
